title: David Toholj MATF
remote_theme: cotes2020/jekyll-theme-chirpy
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

# Appearance
theme_mode: dark
avatar: 
lang: sr

sass:
  style: compressed

# GitHub Pages project site settings
url: https://DavidT01.github.io
baseurl: /davidt01.github.io
